# Generated by Django 6.0.5 on 2026-05-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='books/'),
        ),
    ]
